GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWUyZDQ5MDVjNTA1YWM0OTdjNGFkMyIsImlhdCI6MTYzMzU2NTg3NiwiZXhwIjoxNjMzNTY5NDc2fQ.QjVePkspCds6uAixf1uvEi8OONv-xgQTweuFgRk270U
Content-Type: application/json

{
    "nome":"user1",
    "email":"user1@mail.com",
    "senha":"12345"
}

###
GET http://localhost:3000/usuarios/search?nome=user1
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWUyZDQ5MDVjNTA1YWM0OTdjNGFkMyIsImlhdCI6MTYzMzU2NTg3NiwiZXhwIjoxNjMzNTY5NDc2fQ.QjVePkspCds6uAixf1uvEi8OONv-xgQTweuFgRk270U

###
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "nome":"user1",
    "senha":"12345"
}

GET http://localhost:3000/livros
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWUyZDQ5MDVjNTA1YWM0OTdjNGFkMyIsImlhdCI6MTYzMzU2NTg3NiwiZXhwIjoxNjMzNTY5NDc2fQ.QjVePkspCds6uAixf1uvEi8OONv-xgQTweuFgRk270U