
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWY4NjdmZDQ1Yzc0ZTBlZDFiNGU4YyIsImlhdCI6MTYzNDg2MDU0NiwiZXhwIjoxNjM0ODY0MTQ2fQ.YF6Q-Hr3_x-J98vQepNQFtPUpa8gb-NwEFBIw_LCcuY
Content-Type: application/json

{
    "nome":"user2",
    "email":"user2@mail.com",
    "senha":"12346565"
}

###
GET http://localhost:3000/usuarios/615f859dd45c74e0ed1b4e88
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWY4NjdmZDQ1Yzc0ZTBlZDFiNGU4YyIsImlhdCI6MTYzNDg2MDU0NiwiZXhwIjoxNjM0ODY0MTQ2fQ.YF6Q-Hr3_x-J98vQepNQFtPUpa8gb-NwEFBIw_LCcuY

###
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "nome":"user2",
    "senha":"12346565"
}

###
GET http://localhost:3000/livros
